### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by cesasol** [numixproject/numix-kde-theme#2]
As I am currently working on missing icons for KDE, I just finished updating the qt-curve issue sought to unify the appearance gtk3.
How could I send my changes to revision?

**Comment by bil-elmoussaoui** [comment]
@khurshid-alam this can be closed now ? :+1:

**Comment by khurshid-alam** [comment]
@cesasol I am closing this issue. But if you made progress with qt-curve with qt5 please open a PR.
