### ISSUE TITLE
More love in Kde Please

### ISSUE THREAD

**Issue by Fabrisiri** [numixproject/numix-kde-theme#8]
Dear developers, I love Numix but I also love kde, I'm currently using this theme on Plasma 5.10, and it's great, but you see it being little developed, please put more love and more care in it, I know the main developer now cures Papirus And Arc KDE which are also great for them, but more care for Numix kde would be great, thank you for your work

**Comment by varlesh** [comment]
Devs don't want support (love) KDE, see my PR's.

**Comment by khurshid-alam** [comment]
That's not it. Nobody reviewed that PR properly so far. (Also I do not get any notification of these PRs and comments in time)

**Comment by omni6** [comment]
tristful... wakeup! because it looks great: [varlesh's fork on Archlinux](https://imgur.com/a/EF8Hd)

**Comment by Foggalong** [comment]
Finally got around to doing a proper review of the PR, thanks for being so patient with the time it's taken. I'm not a KDE user but hot damn it looks amazing! I've merged it into our master and made some minor corrections to errors in the make file and URL/author tags which were specific to the fork.

I know we've had differences in the past @varlesh, but if you want to come on the Numix team to maintain this I'd welcome you with open arms :smile:
