### ISSUE TITLE
[Request] Are there any plans for a Numix window decoration theme for Plasma?

### ISSUE THREAD

**Issue by smilesbright** [numixproject/numix-kde-theme#9]
Is there a reason this doesn't exist?

If someone created this, would it be accepted under this repository?

This would likely require compilation and a more complicated Makefile.

What licensing requirements are there for publishing such a clone?

**Comment by Foggalong** [comment]
> Is there a reason this doesn't exist?

There's not a KDE theme dev on the Numix team! We've appealed to a couple of people but no one has responded so far.

> If someone created this, would it be accepted under this repository?

Absolutely! Most all the theme so far was written by external contributor @varlesh.

> What licensing requirements are there for publishing such a clone?

Any Numix or Numix-derived work has to be GNU General Public License v3.0 licensed. Bit of a coincidence actually, this afternoon my job is following up with a few people who've started new Numix derived themes (which we welcome people to do!) but have ditched the open source license.
